"""End-to-end Affordance-driven task execution workflow.

Connects:
  Natural Language Utterance
       ↓
  NLU Intent Parser (:class:`~nora_core.intent.Intent`)
       ↓
  Physical Environment (:class:`~nora_core.affordance.environment.WorldState`)
       ↓
  Affordance Scorer (:class:`~nora_core.affordance.scoring.AffordanceScorer`)
       ↓
  Skill Planner (:class:`~nora_core.planner.Planner`)
       ↓
  Execution & World State Transition (:class:`WorkflowResult`)
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from pathlib import Path
import time
from typing import Any

from nora_core.affordance.environment import WorldState
from nora_core.affordance.metrics import AffordanceMetricsLogger
from nora_core.affordance.scoring import AffordanceScore, AffordanceScorer
from nora_core.intent import Intent
from nora_core.planner import Planner, SkillPlan


@dataclass
class WorkflowResult:
    """Result of running an end-to-end affordance workflow step.

    Attributes
    ----------
    utterance:
        The raw input command string.
    intent:
        The parsed structured :class:`~nora_core.intent.Intent`.
    scores:
        List of all evaluated :class:`~nora_core.affordance.scoring.AffordanceScore`s.
    plan:
        Ranked :class:`~nora_core.planner.SkillPlan` list generated by Planner.
    executed_skill:
        The top-ranked skill chosen for execution (or None if no feasible skill).
    success:
        True if the chosen skill executed successfully.
    message:
        Explanation or status message.
    initial_world_state:
        Snapshot of WorldState before execution.
    final_world_state:
        Snapshot of WorldState after execution.
    execution_time_ms:
        Workflow pipeline processing time in milliseconds.
    """

    utterance: str
    intent: Intent
    scores: list[AffordanceScore]
    plan: list[SkillPlan]
    executed_skill: str | None
    success: bool
    message: str
    initial_world_state: WorldState
    final_world_state: WorldState
    execution_time_ms: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        """Convert result to JSON-serializable dictionary."""
        return {
            "utterance": self.utterance,
            "intent": self.intent.to_dict(),
            "executed_skill": self.executed_skill,
            "success": self.success,
            "message": self.message,
            "top_score": self.plan[0].score if self.plan else 0.0,
            "plan_length": len(self.plan),
            "execution_time_ms": round(self.execution_time_ms, 2),
            "scores": [
                {
                    "skill_name": s.skill_name,
                    "usefulness": s.usefulness,
                    "feasibility": s.feasibility,
                    "combined_score": s.combined_score,
                    "breakdown": s.breakdown,
                }
                for s in self.scores
            ],
            "robot_state_after": {
                "gripper_state": self.final_world_state.robot.gripper_state,
                "held_object": self.final_world_state.robot.held_object,
                "current_pose": self.final_world_state.robot.current_pose,
            },
        }


class AffordanceWorkflow:
    """Orchestrates the complete NORA Affordance workflow from speech to execution.

    Parameters
    ----------
    nlu_model_path:
        Optional path to ``nora_nlu_model.json``. If omitted, attempts to locate
        the model at ``ml/models/nora_nlu_model.json`` or falls back to heuristic parsing.
    world_state:
        Optional initial WorldState. Defaults to :meth:`WorldState.default()`.
    top_k:
        Maximum number of ranked skill plans to generate (default 3).
    score_threshold:
        Minimum combined affordance score required for execution (default 0.25).
    metrics_logger:
        Optional :class:`AffordanceMetricsLogger` instance for recording scores.
    """

    def __init__(
        self,
        nlu_model_path: str | Path | None = None,
        world_state: WorldState | None = None,
        top_k: int = 3,
        score_threshold: float = 0.25,
        metrics_logger: AffordanceMetricsLogger | None = None,
    ) -> None:
        self.world_state = world_state if world_state is not None else WorldState.default()
        self.top_k = top_k
        self.score_threshold = score_threshold
        self.metrics_logger = metrics_logger or AffordanceMetricsLogger()

        # Load local ML parser
        self._parser = self._init_parser(nlu_model_path)
        self._planner = Planner(top_k=top_k)

    def _init_parser(self, path: str | Path | None) -> Any:
        """Initialize local parser with graceful resolution."""
        # Check standard model locations if no path specified
        if path is None:
            candidates = [
                Path("ml/models/nora_nlu_model.json"),
                Path(__file__).resolve().parents[3] / "ml" / "models" / "nora_nlu_model.json",
            ]
            for c in candidates:
                if c.exists():
                    path = c
                    break

        try:
            from ros2_ws.src.nora_nlu_node.nora_nlu_node.local_parser import LocalMLParser
            return LocalMLParser(model_path=str(path) if path else "")
        except ImportError:
            # Fallback to direct inference import from ml
            try:
                from nora_nlu.inference import NLUParser
                return NLUParser(model_path=path)
            except ImportError:
                return None

    def parse_intent(self, utterance: str) -> Intent:
        """Parse natural language command into validated Intent."""
        if self._parser is not None:
            raw_dict = self._parser.parse(utterance)
            return Intent.from_dict(raw_dict)

        # Basic fallback parser if no ML parser is loaded
        action = "unknown"
        lower = utterance.lower()
        if "pick" in lower or "grab" in lower or "thirsty" in lower:
            action = "pick"
        elif "place" in lower or "put" in lower:
            action = "place"
        elif "open" in lower:
            action = "open_gripper"
        elif "close" in lower:
            action = "close_gripper"
        elif "home" in lower:
            action = "go_home"

        return Intent.from_dict({
            "raw_text": utterance,
            "action": action,
            "confidence": 0.85,
        })

    def run(
        self,
        utterance: str,
        world_state_override: WorldState | None = None,
        execute: bool = True,
    ) -> WorkflowResult:
        """Execute full end-to-end workflow for *utterance*.

        Parameters
        ----------
        utterance:
            Natural language command (e.g. ``"pick up the water glass"``, ``"I am thirsty"``).
        world_state_override:
            Optional WorldState override for this specific run.
        execute:
            If True, simulates state transition effects of the top skill.

        Returns
        -------
        WorkflowResult
            Comprehensive report including Intent, AffordanceScores, SkillPlan,
            and execution results.
        """
        start_time = time.perf_counter()
        initial_state = world_state_override if world_state_override is not None else self.world_state
        state_copy = copy.deepcopy(initial_state)

        # 1. Natural Language Intent Parsing
        intent = self.parse_intent(utterance)

        # 2. Affordance Scoring across all candidate skills
        scorer = AffordanceScorer(world_state=state_copy)
        scores = scorer.score_all_skills(intent)

        # Log metrics
        now = time.time()
        for s in scores:
            self.metrics_logger.log_score(
                s,
                timestamp=now,
                intent_action=intent.action.value if hasattr(intent.action, "value") else str(intent.action),
                target_object=intent.target_object,
            )

        # 3. Planning & Ranking
        all_plans = self._planner.rank_skills(intent, scores)

        # Filter plans below feasibility/usefulness threshold
        viable_plans = [p for p in all_plans if p.score >= self.score_threshold]

        executed_skill: str | None = None
        success = False
        message = ""

        if not viable_plans:
            message = (
                f"No viable skill passed affordance threshold ({self.score_threshold}). "
                f"Top candidate was '{all_plans[0].skill_name}' with score {all_plans[0].score:.3f}."
            )
            final_state = state_copy
        else:
            top_plan = viable_plans[0]
            executed_skill = top_plan.skill_name

            if execute:
                success, message = self._execute_skill(top_plan.skill_name, intent, state_copy)
            else:
                success = True
                message = f"Skill '{executed_skill}' selected with affordance score {top_plan.score:.3f} (dry run)."

            final_state = state_copy
            # Update workflow internal state if no override was passed
            if world_state_override is None:
                self.world_state = state_copy

        elapsed_ms = (time.perf_counter() - start_time) * 1000.0

        return WorkflowResult(
            utterance=utterance,
            intent=intent,
            scores=scores,
            plan=viable_plans,
            executed_skill=executed_skill,
            success=success,
            message=message,
            initial_world_state=initial_state,
            final_world_state=final_state,
            execution_time_ms=elapsed_ms,
        )

    def _execute_skill(
        self,
        skill_name: str,
        intent: Intent,
        world: WorldState,
    ) -> tuple[bool, str]:
        """Simulate physical execution of *skill_name* on *world*."""
        robot = world.robot

        if skill_name == "pick":
            target = intent.target_object or "object"
            obj = world.get_or_create_object(target)
            if not robot.is_reachable(*obj.position):
                return False, f"Execution failed: object '{target}' unreachable at {obj.position}."
            if robot.held_object is not None:
                return False, f"Execution failed: gripper already holding '{robot.held_object}'."

            # Transition state
            robot.gripper_state = "holding"
            robot.held_object = target
            obj.is_grasped = True
            return True, f"Successfully executed 'pick': now holding '{target}'."

        elif skill_name == "place":
            if robot.held_object is None:
                return False, "Execution failed: gripper is not holding any object."

            held = robot.held_object
            destination = intent.target_location or "table"
            loc = world.get_or_create_location(destination)
            if not loc.reachable:
                return False, f"Execution failed: target location '{destination}' is unreachable."

            # Transition state
            robot.gripper_state = "open"
            robot.held_object = None
            if held in world.objects:
                world.objects[held].is_grasped = False
                world.objects[held].position = loc.position
            return True, f"Successfully executed 'place': placed '{held}' at '{destination}'."

        elif skill_name == "open_gripper":
            if robot.held_object is not None:
                held = robot.held_object
                robot.held_object = None
                if held in world.objects:
                    world.objects[held].is_grasped = False
            robot.gripper_state = "open"
            return True, "Successfully executed 'open_gripper': gripper is now open."

        elif skill_name == "close_gripper":
            robot.gripper_state = "closed"
            return True, "Successfully executed 'close_gripper': gripper is now closed."

        elif skill_name == "go_home":
            robot.current_pose = "home"
            return True, "Successfully executed 'go_home': arm returned to home pose."

        elif skill_name == "move_to_pose":
            robot.current_pose = "target_pose"
            return True, "Successfully executed 'move_to_pose': arm moved to specified pose."

        return False, f"Unknown skill '{skill_name}'."
